language: cpp
dist: bionic
compiler:
- clang
os:
- linux
env:
  global:
  - secure: dV4afOeNl9/wBLRaIzqBD0NoNDP66qcsyAl7KH8fo4eH2HGdxV6sDX2EKcW44l7fJH6pS3qKX1ZDREnIyjWs9Ktms/F1oSe9unF1CH84DeIWkDHwpIEccEQ66i5DfTlZbmeo2Bp2qnRnMuS/9uSHvnmHOG29rh0rjnPGXcRX4KMYXShwmlv5y6tdvCfa9BoUaQnaQx9VUP/uXiqczS73BBzX5PAn0VV7B3X31i3AB90SWY0PmQDOM7zWkH9w8fd9kNo+sINAScfgEDV2yAwvrdFx/D4VRVecEi4W/O00xZGcDy2Sib81lz2m0pMmMBLp/ewT9N8erDfWH1pls9eN5gtCoSTn5pVxgTGZW2tr821YKaIiySFbgjL4nwGa6Rjsu7n94LTHZ/haReSnk5wKxvI2dwXSsS+rVA+0cqzWGZ1l4z+780f38nM58Yg3vSs8OKQpUnFjV0ZaN5sGnDCiccpp6lvidDbd3rNZff7putuK+qw//xQShEYqFnRUcuz4ZFx8U8CcOVvY3eNlZrqv44I/9UeHDQwEvD/XRz/QfYsdJWDPvWu8KAmD4QIqNSurDJLVRoQp40BH/vrpB8zOzEcynsriclqj5pJyEUdk0KYeCP1Pw8S6sWjfkmPzmyDjZCY9e/m2mF+p+WaQc3VkpayIBmBpLBIMh7uIm4VHP+A=
  - secure: gCWeHvAJJQw/FoOEl618GAnsrX5H4fYWLQR31RGQlq5BypjTjMJYczx+NeGKZHv959uE4jYAlWh57BKgrquEN04oQx19NM1B+k6SCQWjoz7eOks3to5pcOSvadbQFBtf9MKlubvstqozfKZM/s9ugpRZBPameWCd624cIbM1NPhRLWrmXQQlHnGiLYFZgVTisQvjZ9OXIQ3YGX4zzAkpE7SqFgPNJo+xh7Hnhhr9CwB/JWPY5aVbhzuyCGozQu//MBpRSFU/FFs/lAgf997jfOSq3R/78nPOcxEMaEqaaFdKPOkydlKa6GHLUvPLWfJ1nG1NlpzSIkHHXQhO7E/qwbMX++/gRQd9Yv97sQLEJmc2+C7RXy3LY04yPoy+hcGLdOyXizr2+eJYuW47JNNhS8u3PYWhTFw3FMCKyl0Wq0P/dI3MXlQgHY+rpGnj3nWzEoa0ydR75gn2f+sKk+8AyZFyW2BV84i9sFLruqxJOncGSJaRJq0CqaeTN90EPfMagYU/I+esZ5jUuEcrzpLgU8Gu3/YmhaRejumCQ9fw5vS+nVx8iMqMTtwEJ7A95em0/FLqD5SxsaDoKGsAugoP5L3zGw8RR4SZcwfJoCM0SlJg3D9FHjmV7OrwntXj5eu31RPPlW7IV//BuJ3F6R78iESyi9bO4vd+hyZaNfMszQ8=
before_install:
- sudo apt-get update
script:
- if [ -n "$TRAVIS_TAG" ]; then travis_wait 60 sudo ./travis/build-deb.sh; fi
deploy:
- provider: bintray
  file: deploy-lib.json
  skip_cleanup: true
  on:
    tags: true
  user: agerasimov@twilio
  key: "${BINTRAY_TOKEN}"
- provider: bintray
  file: deploy-dev.json
  skip_cleanup: true
  on:
    tags: true
  user: agerasimov@twilio
  key: "${BINTRAY_TOKEN}"
