language: cpp
dist: bionic
compiler:
- clang
os:
- linux
env:
  global:
  - secure: gCWeHvAJJQw/FoOEl618GAnsrX5H4fYWLQR31RGQlq5BypjTjMJYczx+NeGKZHv959uE4jYAlWh57BKgrquEN04oQx19NM1B+k6SCQWjoz7eOks3to5pcOSvadbQFBtf9MKlubvstqozfKZM/s9ugpRZBPameWCd624cIbM1NPhRLWrmXQQlHnGiLYFZgVTisQvjZ9OXIQ3YGX4zzAkpE7SqFgPNJo+xh7Hnhhr9CwB/JWPY5aVbhzuyCGozQu//MBpRSFU/FFs/lAgf997jfOSq3R/78nPOcxEMaEqaaFdKPOkydlKa6GHLUvPLWfJ1nG1NlpzSIkHHXQhO7E/qwbMX++/gRQd9Yv97sQLEJmc2+C7RXy3LY04yPoy+hcGLdOyXizr2+eJYuW47JNNhS8u3PYWhTFw3FMCKyl0Wq0P/dI3MXlQgHY+rpGnj3nWzEoa0ydR75gn2f+sKk+8AyZFyW2BV84i9sFLruqxJOncGSJaRJq0CqaeTN90EPfMagYU/I+esZ5jUuEcrzpLgU8Gu3/YmhaRejumCQ9fw5vS+nVx8iMqMTtwEJ7A95em0/FLqD5SxsaDoKGsAugoP5L3zGw8RR4SZcwfJoCM0SlJg3D9FHjmV7OrwntXj5eu31RPPlW7IV//BuJ3F6R78iESyi9bO4vd+hyZaNfMszQ8=
before_install:
- sudo apt-get update
script:
- if [ -n "$TRAVIS_TAG" ]; then travis_wait 60 sudo ./travis/build-deb.sh buster; fi
- if [ -n "$TRAVIS_TAG" ]; then travis_wait 60 sudo ./travis/build-deb.sh stretch; fi
deploy:
- provider: bintray
  file: deploy-buster-lib.json
  skip_cleanup: true
  on:
    tags: true
  user: agerasimov@twilio
  key: "${BINTRAY_TOKEN}"
- provider: bintray
  file: deploy-buster-dev.json
  skip_cleanup: true
  on:
    tags: true
  user: agerasimov@twilio
  key: "${BINTRAY_TOKEN}"
- provider: bintray
  file: deploy-stretch-lib.json
  skip_cleanup: true
  on:
    tags: true
  user: agerasimov@twilio
  key: "${BINTRAY_TOKEN}"
- provider: bintray
  file: deploy-stretch-dev.json
  skip_cleanup: true
  on:
    tags: true
  user: agerasimov@twilio
  key: "${BINTRAY_TOKEN}"
